PRAGMA foreign_keys = OFF;
PRAGMA ignore_check_constraints = OFF;
PRAGMA auto_vacuum = NONE;
PRAGMA secure_delete = OFF;
BEGIN TRANSACTION;


CREATE TABLE IF NOT EXISTS urls (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	path TEXT NOT NULL,
	url TEXT NOT NULL
);

COMMIT;
